import {leerPedido,totalArmado,inventario,cambiosPedido,clienteDelMensaje,fechaComprobante} from '../js/pedido.js';
import {moneda,normalizar} from '../js/carrito.js';
const $=s=>document.querySelector(s),marca=document.body.dataset.marca,clave='spot.'+document.body.dataset.clave+'.armar.';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalogo=[],pedido=null,seleccionado=null;
const clientesEnMemoria=new Map();
const aviso=t=>$('#aviso').textContent=t;
export function precioEditable(s){s=String(s??'').trim();if(!s)return null;if(!/^(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d{1,2})?$/.test(s))throw Error('Usá pesos con formato argentino, por ejemplo 12.500.');const n=Number(s.replace(/\./g,'').replace(',','.'));if(!Number.isSafeInteger(n)||n<0||n>1e9)throw Error('Indicá un precio entero en pesos.');return n;}
function validarGuardado(p){return p&&p.version===1&&/^W-[A-Z0-9]{4,32}$/.test(p.numero)&&Array.isArray(p.lineas)&&p.lineas.length>0&&p.lineas.length<=1000&&p.lineas.every(l=>/^[\w-]{1,64}$/.test(l.codigo)&&typeof l.nombre==='string'&&l.nombre.length<=180&&Number.isSafeInteger(l.solicitada)&&l.solicitada>0&&l.solicitada<=999&&Number.isSafeInteger(l.entregada)&&l.entregada>=0&&l.entregada<=l.solicitada&&(l.precio===null||Number.isSafeInteger(l.precio)&&l.precio>=0&&l.precio<=1e9)&&['pendiente','todo','menos','no'].includes(l.revision)&&typeof l.enCaja==='boolean');}
function guardados(){try{const lista=Object.keys(localStorage).filter(k=>k.startsWith(clave)).map(k=>k.slice(clave.length)).filter(k=>/^W-[A-Z0-9]{4,32}$/.test(k));$('#guardados').innerHTML='<option value="">Elegí un pedido</option>'+lista.map(n=>`<option>${esc(n)}</option>`).join('');}catch{aviso('Almacenamiento bloqueado: podés trabajar en memoria.');}}
function guardar(){try{localStorage.setItem(clave+pedido.numero,JSON.stringify({version:pedido.version,numero:pedido.numero,fecha:pedido.fecha,lineas:pedido.lineas}));guardados();}catch{aviso('No se pudo guardar: el pedido sigue en memoria. Copiá el comprobante antes de cerrar.');}}
function cargar(numero){try{const s=localStorage.getItem(clave+numero);if(!s)return null;const p=JSON.parse(s);if(!validarGuardado(p))throw Error();return p;}catch{aviso('No se pudo recuperar ese pedido. Pegá nuevamente el mensaje.');return null;}}
function resumen(){const revisados=pedido.lineas.filter(l=>l.revision!=='pendiente').length,caja=pedido.lineas.filter(l=>l.entregada>0&&l.enCaja).length;$('#progreso').textContent=`${revisados} de ${pedido.lineas.length} revisados · ${caja} en la caja`;$('#barra').max=pedido.lineas.length;$('#barra').value=revisados;$('#total').textContent=moneda(totalArmado(pedido.lineas));const sin=pedido.lineas.filter(l=>l.revision!=='pendiente'&&l.entregada>0&&l.precio===null).length;$('#faltantes').textContent=sin?`${sin} renglones sin precio, fuera del total.`:revisados<pedido.lineas.length?'Total parcial: quedan productos por revisar.':'Total de los artículos revisados.';}
function render(){if(!pedido)return;$('#trabajo').hidden=false;$('#numero').textContent=pedido.numero;$('#lineas').innerHTML=pedido.lineas.map((l,i)=>{const p=catalogo.find(p=>p.id===l.codigo),foto=p?.fotos[0]?.src;return `<article class="linea" data-linea="${i}">${foto&&/^assets\/[\w./-]+\.webp$/.test(foto)&&!foto.includes('..')?`<img src="../${esc(foto)}" alt="${esc(l.nombre)}" loading="lazy">`:'<span class="foto-pendiente">Foto pendiente</span>'}<div><span class="codigo">${esc(l.codigo)}</span><h3>${esc(l.nombre)}</h3><p>Solicitadas: ${l.solicitada} unidades${!p?' · Fuera del catálogo':''}</p><div class="opciones">${[['todo','Hay todo'],['menos','Hay menos'],['no','No hay']].map(([v,t])=>`<button type="button" data-revision="${v}" aria-pressed="${l.revision===v}">${t}</button>`).join('')}</div><div class="campos"><label>Cantidad a entregar<input type="number" data-entregada min="${l.revision==='menos'?1:0}" max="${l.revision==='menos'?l.solicitada-1:l.solicitada}" step="1" value="${l.entregada}" ${l.revision==='menos'?'':'disabled'}></label><label>Precio por unidad (ARS)<input data-precio inputmode="decimal" value="${l.precio??''}" placeholder="Consultar"></label></div><label class="caja"><input type="checkbox" data-caja ${l.enCaja?'checked':''} ${l.revision==='pendiente'||l.entregada===0?'disabled':''}>Lo puse en la caja</label></div></article>`;}).join('');resumen();}
let conflicto=null;
function abrirPedido(p,cliente){pedido=p;if(!pedido.fecha||!Number.isFinite(Date.parse(pedido.fecha)))pedido.fecha=new Date().toISOString();if(cliente)clientesEnMemoria.set(p.numero,cliente);$('#mensaje').value='';guardar();render();aviso('Pedido abierto. Revisá precios y cantidades antes de armar.');}
$('#importar').onclick=()=>{try{
  const texto=$('#mensaje').value,nuevo=leerPedido(texto,catalogo),guardado=cargar(nuevo.numero),cliente=clienteDelMensaje(texto);
  if(!guardado){abrirPedido(nuevo,cliente);return;}
  conflicto={nuevo,guardado,cliente};
  $('#conflicto-numero').textContent=nuevo.numero;
  const cambios=cambiosPedido(guardado,nuevo);
  $('#conflicto-cambios').textContent=cambios.length?cambios.join('\n'):'Los códigos y cantidades solicitadas coinciden.';
  $('#conflicto').showModal();$('#conservar-pedido').focus();
}catch(e){aviso(e.message);}};
$('#conservar-pedido').onclick=()=>{if(!conflicto)return;abrirPedido(conflicto.guardado,conflicto.cliente);$('#conflicto').close();aviso('Se conservó el armado guardado, con sus precios y revisiones.');};
$('#reemplazar-pedido').onclick=()=>{if(!conflicto)return;abrirPedido(conflicto.nuevo,conflicto.cliente);$('#conflicto').close();aviso('Mensaje nuevo cargado. Revisá nuevamente todos los artículos.');};
$('#cancelar-conflicto').onclick=()=>$('#conflicto').close();
$('#conflicto').onclose=()=>{conflicto=null;$('#importar').focus();};
$('#guardados').onchange=()=>{const p=cargar($('#guardados').value);if(p){pedido=p;if(!pedido.fecha||!Number.isFinite(Date.parse(pedido.fecha)))pedido.fecha=new Date().toISOString();render();aviso('Armado recuperado. Para incluir nombre y teléfono en el comprobante, pegá el mensaje original y elegí Conservar.');}};
$('#lineas').onclick=e=>{const b=e.target.closest('[data-revision]');if(!b)return;const i=Number(b.closest('[data-linea]').dataset.linea),l=pedido.lineas[i];if(b.dataset.revision==='menos'&&l.solicitada===1){aviso('Para una unidad: elegí Hay todo o No hay.');return;}l.revision=b.dataset.revision;l.entregada=l.revision==='no'?0:l.revision==='todo'?l.solicitada:Math.max(1,l.solicitada-1);l.enCaja=false;guardar();render();const target=$(`[data-linea="${i}"] [data-revision="${l.revision}"]`);target.focus();};
function editarLinea(e){const el=e.target,i=Number(el.closest('[data-linea]')?.dataset.linea);if(!Number.isInteger(i))return;const l=pedido.lineas[i];try{if(el.hasAttribute('data-entregada')){const n=Number(el.value);if(!Number.isSafeInteger(n)||n<1||n>=l.solicitada)throw Error('Hay menos requiere una cantidad entre 1 y la solicitada menos 1.');l.entregada=n;l.enCaja=false;el.closest('.linea').querySelector('[data-caja]').checked=false;}if(el.hasAttribute('data-precio'))l.precio=precioEditable(el.value);if(el.hasAttribute('data-caja'))l.enCaja=el.checked;el.setCustomValidity('');guardar();resumen();aviso('Cambio guardado.');}catch(error){el.setCustomValidity(error.message);if(e.type==='change')el.reportValidity();aviso(error.message);}}
$('#lineas').addEventListener('change',editarLinea);
$('#lineas').addEventListener('input',e=>{if(e.target.matches('[data-precio],[data-entregada]'))editarLinea(e);});
$('#buscar').oninput=()=>{const q=normalizar($('#buscar').value);$('#busqueda').innerHTML=q.length<2?'':catalogo.filter(p=>normalizar(p.id+' '+p.nombre).includes(q)).slice(0,10).map(p=>`<button class="busqueda-item" type="button" data-elegir="${esc(p.id)}">${esc(p.id)} · ${esc(p.nombre)} · ${p.precio===null?'Consultar':moneda(p.precio)}</button>`).join('');};
$('#busqueda').onclick=e=>{const id=e.target.closest('[data-elegir]')?.dataset.elegir;seleccionado=catalogo.find(p=>p.id===id);if(!seleccionado)return;$('#nuevo-codigo').value=seleccionado.id;$('#nuevo-nombre').value=seleccionado.nombre;$('#nuevo-precio').value=seleccionado.precio??'';$('#nuevo-cantidad').focus();};
$('#sumar').onsubmit=e=>{e.preventDefault();try{const cantidad=Number($('#nuevo-cantidad').value),nombre=$('#nuevo-nombre').value.trim(),codigo=$('#nuevo-codigo').value.trim().toUpperCase()||'MANUAL-'+(pedido.lineas.length+1);if(!nombre||!Number.isSafeInteger(cantidad)||cantidad<1||cantidad>999||!/^[\w-]{1,64}$/.test(codigo))throw Error('Revisá nombre, código y cantidad.');if(pedido.lineas.some(l=>l.codigo===codigo))throw Error('Ese código ya está en el pedido. Para evitar duplicados, revisá el renglón existente.');pedido.lineas.push({codigo,nombre,solicitada:cantidad,entregada:cantidad,precio:precioEditable($('#nuevo-precio').value),revision:'pendiente',enCaja:false});guardar();render();$('#sumar').reset();$('#busqueda').innerHTML='';$('#buscar').value='';aviso('Producto sumado; falta revisarlo.');}catch(e){aviso(e.message);}};
function textoComprobante(conMarca=true){const cliente=clientesEnMemoria.get(pedido.numero)||{},lineas=pedido.lineas,pendientes=lineas.filter(l=>l.revision==='pendiente').length;return [conMarca?marca:'','Pedido '+pedido.numero,'Fecha: '+fechaComprobante(pedido.fecha),cliente.nombre?'Cliente: '+cliente.nombre:'',cliente.telefono?'Teléfono: '+cliente.telefono:'',pendientes?'BORRADOR: '+pendientes+' renglones pendientes de revisar.':'',...lineas.filter(l=>l.revision!=='pendiente'&&l.entregada>0).map(l=>`${l.entregada} × ${l.nombre} [${l.codigo}] — ${l.precio===null?'precio a confirmar':moneda(l.precio)+' c/u · '+moneda(l.precio*l.entregada)}${l.enCaja?'':' · pendiente de poner en caja'}`),...lineas.filter(l=>l.revision==='no').map(l=>'No disponible: '+l.nombre+' ['+l.codigo+']'),'',`Total: ${moneda(totalArmado(lineas))}`,lineas.some(l=>l.entregada>0&&l.precio===null)?'Hay productos sin precio, fuera del total.':'','No es factura.'].filter(Boolean).join('\n');}
$('#ver-comprobante').onclick=()=>{const bad=[...$('#lineas').querySelectorAll('input')].find(i=>!i.checkValidity());if(bad){bad.reportValidity();return;}$('#recibo-texto').textContent=textoComprobante(false);$('#comprobante').showModal();$('#cerrar-comprobante').focus();};
$('#cerrar-comprobante').onclick=()=>$('#comprobante').close();$('#comprobante').onclose=()=>$('#ver-comprobante').focus();
async function copiar(texto){try{await navigator.clipboard.writeText(texto);aviso('Copiado.');$('#copia-estado').textContent='Texto copiado para WhatsApp.';}catch{aviso('No se pudo copiar automáticamente; seleccioná el texto del comprobante.');$('#copia-estado').textContent='Seleccioná el texto y usá Copiar.';}}
$('#copiar-comprobante').onclick=()=>copiar(textoComprobante());$('#imprimir').onclick=()=>window.print();$('#inventario').onclick=()=>{const bad=[...$('#lineas').querySelectorAll('input')].find(i=>!i.checkValidity());if(bad){bad.reportValidity();return;}const texto=inventario(pedido.lineas);if(!texto){aviso('Todavía no hay artículos revisados y puestos en la caja.');return;}copiar(texto);};
$('#borrar').onclick=()=>{try{localStorage.removeItem(clave+pedido.numero);}catch{aviso('No se pudo borrar el guardado; revisá los permisos de almacenamiento.');return;}clientesEnMemoria.delete(pedido.numero);pedido=null;$('#trabajo').hidden=true;$('#lineas').innerHTML='';guardados();aviso('Pedido borrado de este navegador.');};
try{const r=await fetch('../data/productos.json',{cache:'no-store'});if(!r.ok)throw Error();catalogo=(await r.json()).productos;guardados();}catch{aviso('No se pudo cargar el catálogo. Recargá antes de importar.');$('#importar').disabled=true;}
